export const songsList = [
  {
    id: "s1",
    link: "/",
    img: "c1.jpg",
    title: "Peaceful Piano",
    about: "Relax and indulge with beautiful piano pieces.",
  },
  {
    id: "s2",
    link: "/",
    img: "c2.jpg",
    title: "Deep Focus",
    about: "Keep calm and focus with ambient and post-rock music.",
  },
  {
    id: "s3",
    link: "/",
    img: "c3.jpg",
    title: "Instrumental Study",
    about: "Focus with soft study music in the background.",
  },
  {
    id: "s4",
    link: "/",
    img: "c4.jpg",
    title: "Jazz Vibes",
    about: "The original chill instrumental beats playlist.",
  },
  {
    id: "s5",
    link: "/",
    img: "c5.jpg",
    title: "Focus Flow",
    about: "Uptempo instrumental hip hop beats.",
  },
  {
    id: "s5",
    link: "/",
    img: "c5.jpg",
    title: "Focus Flow",
    about: "Uptempo instrumental hip hop beats.",
  },
];
// ---------------------------------------------------------------
export const spotifyPlaylists = [
  {
    id: "p1",
    link: "/",
    img: "p1.jpg",
    title: "Viva Latino",
    about: "Today's top Latin hits, elevando nuestra música. Cover: Manuel Turizo & Marshmello ",
  },
  {
    id: "p2",
    link: "/",
    img: "p2.jpg",
    title: "RapCaviar",
    about: "New music from Nicki Minaj, Don Toliver and BIA.",
  },
  {
    id: "p3",
    link: "/",
    img: "p3.jpg",
    title: "All Out 2010s",
    about: "The biggest songs of the 2010s. ",
  },
  {
    id: "p4",
    link: "/",
    img: "p4.jpg",
    title: "Rock Classics",
    about: "Rock legends & epic songs that continue to inspire generations. Cover: Foo Fighters",
  },
  {
    id: "p5",
    link: "/",
    img: "p5.jpg",
    title: "Chill Hits",
    about: "Kick back to the best new and recent chill hits.",
  },
  {
    id: "p5",
    link: "/",
    img: "p5.jpg",
    title: "Chill Hits",
    about: "Kick back to the best new and recent chill hits.",
  },
  {
    id: "p8",
    link: "/",
    img: "p8.jpg",
    title: "Today's Top Hits",
    about: "KAROL G & Shakira are on top of the Hottest 50!",
  },
];
// ---------------------------------------------------------------
export const categories = [
  {
    id: "categ-1",
    img: "Podcasts.jpg",
    title: "Podcasts",
    color: "rgb(39, 133, 106)",
    link: "/",
  },
  {
    id: "categ-2",
    img: "made for you.png",
    title: "made for you",
    color: "rgb(30, 50, 100)",
    link: "/",
  },
  {
    id: "categ-3",
    img: "charts.jpg",
    title: "charts",
    color: "rgb(141, 103, 171)",
    link: "/",
  },
  {
    id: "categ-4",
    img: "new releases.jpg",
    title: "new releases",
    color: "rgb(232, 17, 91)",
    link: "/",
  },
  {
    id: "categ-5",
    img: "discover.jpeg",
    title: "discover",
    color: "rgb(141, 103, 171)",
    link: "/",
  },
  {
    id: "categ-6",
    img: "live events.jpg",
    title: "live events",
    color: "rgb(115, 88, 255)",
    link: "/",
  },
  {
    id: "categ-7",
    img: "live events.jpg",
    title: "live events",
    color: "rgb(115, 88, 255)",
    link: "/",
  },
  {
    id: "categ-8",
    img: "live events.jpg",
    title: "live events",
    color: "rgb(115, 88, 255)",
    link: "/",
  },
  {
    id: "categ-9",
    img: "live events.jpg",
    title: "live events",
    color: "rgb(115, 88, 255)",
    link: "/",
  },
  {
    id: "categ-10",
    img: "live events.jpg",
    title: "live events",
    color: "rgb(115, 88, 255)",
    link: "/",
  },
  {
    id: "categ-11",
    img: "live events.jpg",
    title: "live events",
    color: "rgb(115, 88, 255)",
    link: "/",
  },
];

export const playListsSongs = [
  {
    id: "1",
    img: "tr-1.jpg",
    title: "So Far So Good",
    author: "Sun Of They",
    album: "Silent Hills",
    dateAdded: "5 days ago",
    duration: "2:31",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "2",
    img: "tr-2.jpg",
    title: "Apricity",
    author: "Imala Zir",
    album: "Apricity",
    dateAdded: "5 days ago",
    duration: "2:38",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "3",
    img: "tr-3.jpg",
    title: "Solatium",
    author: "Imber Sun",
    album: "Solatium",
    dateAdded: "5 days ago",
    duration: "2:06",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "4",
    img: "tr-4.jpg",
    title: "efflorescence",
    author: "Far & Beyond",
    album: "efflorescence",
    dateAdded: "5 days ago",
    duration: "2:23",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "5",
    img: "tr-5.jpg",
    title: "Gather My Thoughts",
    author: "Josef Briem",
    album: "Gather My Thoughts",
    dateAdded: "5 days ago",
    duration: "3:03",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "6",
    img: "tr-6.jpg",
    title: "Fresh Paint",
    author: "Shape Of Our Dreams",
    album: "Mind games",
    dateAdded: "5 days ago",
    duration: "2:34",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "7",
    img: "tr-6.jpg",
    title: "Fresh Paint",
    author: "Shape Of Our Dreams",
    album: "Mind games",
    dateAdded: "5 days ago",
    duration: "2:34",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "8",
    img: "tr-6.jpg",
    title: "Fresh Paint",
    author: "Shape Of Our Dreams",
    album: "Mind games",
    dateAdded: "5 days ago",
    duration: "2:34",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "9",
    img: "tr-6.jpg",
    title: "Fresh Paint",
    author: "Shape Of Our Dreams",
    album: "Mind games",
    dateAdded: "5 days ago",
    duration: "2:34",
    more: "",
    library: "",
    link: "/",
  },
  {
    id: "10",
    img: "tr-6.jpg",
    title: "Fresh Paint",
    author: "Shape Of Our Dreams",
    album: "Mind games",
    dateAdded: "5 days ago",
    duration: "2:34",
    more: "",
    library: "",
    link: "/",
  },
  // {
  //   id: "",
  //   img: "",
  //   title: "",
  //   author: "",
  //   album: "",
  //   dateAdded: "",
  //   duration: "",
  //   more: "",
  //   library: "",
  //   link: "/",
  // },
];